name: kaggle-Backpack-Prediction-Challenge
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - numba
  - ipykernel
  - matplotlib
  - seaborn 
  - scikit-learn=1.5.2
  - plotly
  - nbformat>=4.2.0
  - xgboost
  - graphviz 